### ISSUE TITLE
Cover GenericExtensions with unit tests

### ISSUE THREAD

**Issue by Teodor92** [Teodor92/MoreDotNet#9]

**Comment by EgorMatirov** [comment]
Hello. I want to start working on that issue. As for me looks like it's better to test IsBetween method using mocking CompareTo and checking that all returned cases are handled correctly. I didn't find any references to mock framework in project. What do you think about adding dependency on one of mock frameworks? Do you have any preferences or should I choose?

**Comment by Teodor92** [comment]
Strange I thought added Moq to the test project. Anyway - it's added now :)
